openapi: 3.0.3
info:
  title: Bluewhale
  description: 'This is API specifications for bluewhale site'
  version: 1.0.0
servers:
  - url: http://127.0.0.1:4010
paths:
  "/api/v1/me":
    get:
      summary: get current user's profile
      responses:
        '200':
          description: current user
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/User"
                  code:
                    type: integer
  "/api/v1/login":
    options:
      summary: get csrf token
      responses:
        '200':
          description: options
    post:
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginForm"
      responses:
        '200':
          description: success login
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/User"
                  code:
                    type: integer
  "/api/v1/logout":
    post:
      summary: logout
      responses:
        '200':
          description: success logout
  "/api/v1/send-verification":
    post:
      summary: send verification mail
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendVerificationForm"
      responses:
        '200':
          description: success logout
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: integer
                  code:
                    type: integer
  "/api/v1/verify/{token}":
    get:
      parameters:  
        - name: token
          in: path
          description: token。
          required: true
          schema:
            type: string
      summary: verify verification token
      responses:
        '200':
          description: success verify
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/VerifySuccess"
          
  "/api/v1/register":
    post:
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterForm"
      responses:
        '200':
          description: success register
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: "#/components/schemas/User"
                  code:
                    type: integer
                    
  "/api/v1/articles":
    get:
      summary: articles
      responses:
        '200':
          description: get all articles
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Articles"
  "/api/v1/articles/{pk}":
    get:
      summary: articles
      parameters:  
        - name: pk
          in: path
          description: primary key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: get all articles
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Article"
  # 不懂如何把put, post, get, delete 合并到一起
  "/api/v1/user/{userId}":
    get:
      summary: get user
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: get userId's info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    delete:
      summary: delete user
      parameters:
        - name: userId
          in: path
          description: userId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: delete userId's info
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: integer
  "/api/v1/user":
    # 和resister的接口类似 后续需要清理 = =
    post:
      summary: insert user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: insert user info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      summary: update user
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: update user info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
components:
  schemas:
    CommonResponse: # common response which has data and code properties
      type: object
      properties:
        data:
          type: object
        code:
          type: integer
    LoginForm:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          format: password
    SendVerificationForm:
      type: object
      properties:
        email:
          type: string
          format: email
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        email:
          type: string
          format: email
        phone:
          type: string
        nickname:
          type: string
        date_joined:
          type: string
          format: date-time
        last_login:
          type: string
          format: date-time
        last_login_ip:
          type: string
          format: ipv4
        description:
          type: string
        groups:
          type: array
          items:
            $ref: "#/components/schemas/Group"
        profilePicture: # 头像
          type: string
        password:
          type: string
        wechat_id:
          type: string
        school:
          type: string
        major:
          type: string
        company:
          type: string
        position:
          type: string
    Group:
      type: object
      properties:
        id:
          type: integer
          format: int64
          minimum: 1
        name:
          type: string
    VerifySuccess:
      type: object
      properties:
        data:
          type: string
        code:
          type: integer
    RegisterForm:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
    Article:
      type: object
      properties:
        id:
          type: string
        author:
          type: string
        title:
          type: string
        content:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        status:
          type: string
    Articles:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/Article"
        code:
          type: integer
        