# Generated by Django 3.2 on 2021-05-17 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210203_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='', max_length=255, verbose_name='公司'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(default='', max_length=255, verbose_name='专业'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=255, verbose_name='职位'),
        ),
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.CharField(default='', max_length=255, verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.CharField(default='', max_length=255, verbose_name='学校'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechatId',
            field=models.CharField(default='', max_length=255, verbose_name='微信号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=255, verbose_name='密码'),
        ),
    ]
